### ISSUE TITLE
LDAP daemon starts with invalid URL parameter and not logging an error

### ISSUE THREAD

**Issue by mfa-inverso** [bitnami/bitnami-docker-nginx-ldap-auth-daemon#10]
**Description**

I was wondering why the LDAP authentication is not working. So I provided a invalid `NGINXLDAP_LDAP_URI` parameter to test what happens. The container is starting fine and not logging an error. For me this is not the desired behaviour. 

**Steps to reproduce the issue:**

- provide invalid `NGINXLDAP_LDAP_URI` parameter 
- start the LDAP daemon 

**Describe the results you received:**

- starting fine 
- not logging an error 

**Describe the results you expected:**

log error that parameters are invalid or can not authenticate at server

**Comment by juan131** [comment]
Hi @mfa-inverso 

I think I can reproduce the issue using the command below:

```
$ docker run --rm -it --env NGINXLDAP_LDAP_URI=some-invalid-url bitnami/nginx-ldap-auth-daemon:latest
 07:53:16.82
 07:53:16.83 Welcome to the Bitnami nginx-ldap-auth-daemon container
 07:53:16.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx-ldap-auth-daemon
 07:53:16.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx-ldap-auth-daemon/issues
 07:53:16.83
 07:53:16.83 INFO  ==> ** Starting NGINX LDAP Auth Daemon setup **
 07:53:16.84 INFO  ==> Validating settings in NGINXLDAP_* env vars
 07:53:16.84 INFO  ==> ** NGINX LDAP Auth Daemon setup finished! **

 07:53:16.85 INFO  ==> ** Starting NGINX LDAP Auth Daemon **
```

Please correct me if I'm wrong but you're expecting some validation that complains when the value set at `NGINXLDAP_LDAP_URI` is invalid, right?

**Comment by mfa-inverso** [comment]
Hi @juan131, 

that is right. I would expect to see if the parameters I provided are incorrect. At the moment I just get a 401 error when I want to authenticate a user. 
When I execute the nginx-ldap-auth-daemon.py script directly it also does not print any output although output should be written with sys.stdout.write.

**Comment by mfa-inverso** [comment]
The behaviour is the same when I run the docker compose example. It seems that the sys.stdout.write output is buffered. 
https://stackoverflow.com/questions/51362213/docker-compose-not-printing-stdout-in-python-app
When I set the env variable PYTHONUNBUFFERED=1 I can see the output immediatelly.

**Comment by fmulero** [comment]
Hi @mfa-inverso, unfortunately as you pointed out that's a problem of `nginx-ldap-auth-daemon.py`. We could validate that `NGINXLDAP_LDAP_URI` has an URI format and we have connectivity but that's no the solution, because you could face also other kinds of problems regarding LDAP like `basedn` not ok, you cannot bind due to TLS error, etc, and those errors should be logged by `nginx-ldap-auth-daemon.py` in a proper way.  Could you open a question about this into the   [upstream project](https://github.com/nginxinc/nginx-ldap-auth/)?.

**Comment by fmulero** [comment]
This issue is like #2
