### ISSUE TITLE
bitnami/bitnami-docker-nginx-ldap-auth-daemon in kubernetes

### ISSUE THREAD

**Issue by Rbsn-joses** [bitnami/bitnami-docker-nginx-ldap-auth-daemon#6]
Good afternoon, I would like to know how would be the simple configuration for this ldap authentication to work in a kubernetes ingress, it works perfectly, but I can't release the graphical interface after that, it gives error 500, I think it's related to bad ingress configuration.

**Comment by yilmi** [comment]
Hi @Rbsn-joses, would you mind providing more details around your configuration (what variables have you been setting, your kubernetes configuration,...)

Based on your initial description, it sounds like this problem can come from anywhere, not necessarily our container 🤔

**Comment by Rbsn-joses** [comment]
so, i think that's not really the problem in this container, but i would like to know if you have a basic configuration for it in kubernetes, it seems ingress redirection error, or something like that. 
https://www.opsmx.com/blog/securing-nginx-ingress-with-ldap/
I was trying to follow this tutorial
with annotations ingress

**Comment by yilmi** [comment]
Hi @Rbsn-joses sorry for the delay, you can use our nginx helm chart, which provides support for this container's configuration - https://github.com/bitnami/charts/tree/master/bitnami/nginx#ldap-parameters
